server {
    listen 80;
    server_name localhost;

    location /attendance/ {
        proxy_pass http://attendance-service:3003/attendance/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
    }

    location /health/attendance {
        proxy_pass http://attendance-service:3003/health;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /files/ {
        proxy_pass http://file-service:3006/files/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
    }

    location /health/file {
        proxy_pass http://file-service:3006/health;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
        proxy_pass http://keycloak:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 200 'VidyaConnect local environment running\n';
        add_header Content-Type text/plain;
    }
}